update: all

schedule: "every day"

branch: mainline

label_prs: pyup

assignees:
  - pzelnip

requirements:
  - requirements/requirements-float.txt:
      update: False
      pin: False
  - requirements.txt:
      update: all
      pin: True
