language: bash

sudo: required

services:
- docker

script:
- make deploy

branches:
  only:
  - master

notifications:
  email: false
  slack:
    secure: "TnZ76DYHqpUEPA4LTIi+j1lHk8vEpqie38nZbD9JDScFlxjrf01qy85S1XyVSbMEZcbiGrxt9ejLCIJY4F3/aUe6yb2V9pQDEj++GMLkITxJFhvB01ZOjxX0TUd/xJohyCwc5QsoryG6Fa09Xs41rFAg20f0YgiucIqr+SKGzOJO6LnCNEJ3dBcN6LtkVa7ze1dzopSC2x+bhzsIgqv78Jo8r5ns+wmZ35Ps+5HPg5DEeAIAJBfip+GXSUZeF/3B0Aze4z3AUsU59P+xh7Ax0ccgQhuJeIbrt8lpDAO0dw27AnfbGyczYswWFIak/EJspWBvJ3/4W5QuPDfSGtzi/NqjS4sPPY93qdH4MFstguwBcnUTUZ9Tyrxgz++1KJJk49+s5ISoF9RpMQgC0Oia/z8aeDhe9U4uHBdnaL8ScAaQv3AF4lKcYzuDNK1SfPpe3nzzaZm6CjtUEqcgRtAre7bfxwngTIlz/Tsm487MWBjap9Bb9YCg1MkNC7njt9oApGwiQfVesFUxqV6N7J1kQjKrJnohp2gDVucdhAnFCYl2IVEuV4EJ/VBUasrFCs4zQVcAeNwIFo2YzlmqnIEH4oXzwZioRedvsKFdAxziUhOaGZ51t5Oz3JKFRYY0081WtDu9UUKNoUPqBCIuL7lE4/CFNO+w0O8EjVOZeGTKijM="
