language: bash

sudo: required

services:
- docker

script:
- make deploy

branches:
  only:
  - mainline

notifications:
  email: false
  slack:
    secure: "km7RBKh+IcKOXPz/CLrjmLStdfbRLlI28bDnApZcZR6rA+iSO9HW8tEYIIPAMq6GDfOcnZgpSw5kiJXDjSyuuXoNjP41D4Uyt8z+q9aXcF3QxUBP44hfcF2M+6XnFNin02nZCRPJutK8nMH+DzspmaEZTraG660Oc3ZZPyE8Gvn7uaIyyB7aJe1NlI2hbOCw7A4A2wvjkmHEnNKmE0tpE7FSxHE0YQ/xj7PGAtot7io603brBneZwkNoQ5t5x8DdoD0IVdyvXQQ/W3WX84ePW02JPpBtNLfN+dnzPeZZO86X6ZTKvQjgOqVUDop+MPcWbPO0Wa8IukKj5Sg7MdXwCs+DhsljXr14Hcm1ynnVstEjKTwHFfLXQjRTmcIc3GcRCBaR5FJNh5SvfousDWpE14Vp48RZ744ac80fgxt3treMCkk9eDacW8l1olYoOn32WkMoI6sHnLn4omLqttqXMi842b+Cmzq3Tip2/9jxGtjC7rM+9KrHq1Naldak3rAVGGzB8IDrHf7o+8R6GCIkaDMb39l0vnOSOhMXFO3DS+VFy6nPu1N3WKn13FUaw4GHkND1gHmvH6YlmpiD0W96cuz9BoHcwenCH1gwUsqRR4nA1n1KfwPrtveufHdzWXVzTKoiB1d90b4gV5/U1OAoA56vU9YrdhxvsHQAKzLRfIw="
