name: Build PR

on:
  pull_request:
    branches: [ mainline ]
  # enable manual running in the actions ui
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Do safety check using the most recent version of the image
    - name: Run Safety on Requirements.txt
      run: cat requirements.txt | docker run -i --rm pyupio/safety safety check --stdin

    - name: Run Safety on Requirements-float.txt
      run: cat requirements-float.txt | docker run -i --rm pyupio/safety safety check --stdin
