name: Build PR

on:
  pull_request:
    branches: [ mainline ]
  # enable manual running in the actions ui
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
            }]
          }
        channel: '#codependentcodr'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() # Pick up events even if the job fails or is canceled.

    # Do safety check using the most recent version of the image
    - name: Run Safety on Requirements.txt
      run: cat requirements.txt | docker run -i --rm pyupio/safety safety check --stdin

    - name: Run Safety on Requirements-float.txt
      run: cat requirements-float.txt | docker run -i --rm pyupio/safety safety check --stdin
