name: Build And Push Image

on:
  push:
    branches: [ mainline ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: pzelnip

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build And Push Image
      shell: 'script -q -e -c "bash {0}"'
      run: make deploy
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
